/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as TitleSlugRouteImport } from './routes/title.$slug'
import { Route as BrowseSeriesRouteImport } from './routes/browse.series'
import { Route as BrowseMoviesRouteImport } from './routes/browse.movies'
import { Route as BrowseDramasRouteImport } from './routes/browse.dramas'
import { Route as BrowseDocumentariesRouteImport } from './routes/browse.documentaries'
import { Route as BrowseCartoonsRouteImport } from './routes/browse.cartoons'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTitlesRouteImport } from './routes/_authenticated/admin/titles'
import { Route as AuthenticatedAdminTaxonomyRouteImport } from './routes/_authenticated/admin/taxonomy'
import { Route as AuthenticatedAdminSyncRouteImport } from './routes/_authenticated/admin/sync'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminTitlesIdRouteImport } from './routes/_authenticated/admin/titles.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSlugRoute = TitleSlugRouteImport.update({
  id: '/title/$slug',
  path: '/title/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSeriesRoute = BrowseSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseMoviesRoute = BrowseMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseDramasRoute = BrowseDramasRouteImport.update({
  id: '/dramas',
  path: '/dramas',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseDocumentariesRoute = BrowseDocumentariesRouteImport.update({
  id: '/documentaries',
  path: '/documentaries',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseCartoonsRoute = BrowseCartoonsRouteImport.update({
  id: '/cartoons',
  path: '/cartoons',
  getParentRoute: () => BrowseRoute,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTitlesRoute =
  AuthenticatedAdminTitlesRouteImport.update({
    id: '/titles',
    path: '/titles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTaxonomyRoute =
  AuthenticatedAdminTaxonomyRouteImport.update({
    id: '/taxonomy',
    path: '/taxonomy',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSyncRoute = AuthenticatedAdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTitlesIdRoute =
  AuthenticatedAdminTitlesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTitlesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRouteWithChildren
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/browse/cartoons': typeof BrowseCartoonsRoute
  '/browse/documentaries': typeof BrowseDocumentariesRoute
  '/browse/dramas': typeof BrowseDramasRoute
  '/browse/movies': typeof BrowseMoviesRoute
  '/browse/series': typeof BrowseSeriesRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/titles': typeof AuthenticatedAdminTitlesRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/titles/$id': typeof AuthenticatedAdminTitlesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRouteWithChildren
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/browse/cartoons': typeof BrowseCartoonsRoute
  '/browse/documentaries': typeof BrowseDocumentariesRoute
  '/browse/dramas': typeof BrowseDramasRoute
  '/browse/movies': typeof BrowseMoviesRoute
  '/browse/series': typeof BrowseSeriesRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/titles': typeof AuthenticatedAdminTitlesRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/titles/$id': typeof AuthenticatedAdminTitlesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRouteWithChildren
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/browse/cartoons': typeof BrowseCartoonsRoute
  '/browse/documentaries': typeof BrowseDocumentariesRoute
  '/browse/dramas': typeof BrowseDramasRoute
  '/browse/movies': typeof BrowseMoviesRoute
  '/browse/series': typeof BrowseSeriesRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/_authenticated/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/_authenticated/admin/titles': typeof AuthenticatedAdminTitlesRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/titles/$id': typeof AuthenticatedAdminTitlesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/pricing'
    | '/search'
    | '/account'
    | '/watchlist'
    | '/browse/cartoons'
    | '/browse/documentaries'
    | '/browse/dramas'
    | '/browse/movies'
    | '/browse/series'
    | '/title/$slug'
    | '/watch/$slug'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/plans'
    | '/admin/reviews'
    | '/admin/sync'
    | '/admin/taxonomy'
    | '/admin/titles'
    | '/admin/users'
    | '/api/public/stripe-webhook'
    | '/admin/'
    | '/admin/titles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/pricing'
    | '/search'
    | '/account'
    | '/watchlist'
    | '/browse/cartoons'
    | '/browse/documentaries'
    | '/browse/dramas'
    | '/browse/movies'
    | '/browse/series'
    | '/title/$slug'
    | '/watch/$slug'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/plans'
    | '/admin/reviews'
    | '/admin/sync'
    | '/admin/taxonomy'
    | '/admin/titles'
    | '/admin/users'
    | '/api/public/stripe-webhook'
    | '/admin/titles/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/pricing'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/watchlist'
    | '/browse/cartoons'
    | '/browse/documentaries'
    | '/browse/dramas'
    | '/browse/movies'
    | '/browse/series'
    | '/title/$slug'
    | '/watch/$slug'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/sync'
    | '/_authenticated/admin/taxonomy'
    | '/_authenticated/admin/titles'
    | '/_authenticated/admin/users'
    | '/api/public/stripe-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/titles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRouteWithChildren
  PricingRoute: typeof PricingRoute
  SearchRoute: typeof SearchRoute
  TitleSlugRoute: typeof TitleSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$slug': {
      id: '/title/$slug'
      path: '/title/$slug'
      fullPath: '/title/$slug'
      preLoaderRoute: typeof TitleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/series': {
      id: '/browse/series'
      path: '/series'
      fullPath: '/browse/series'
      preLoaderRoute: typeof BrowseSeriesRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/browse/movies': {
      id: '/browse/movies'
      path: '/movies'
      fullPath: '/browse/movies'
      preLoaderRoute: typeof BrowseMoviesRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/browse/dramas': {
      id: '/browse/dramas'
      path: '/dramas'
      fullPath: '/browse/dramas'
      preLoaderRoute: typeof BrowseDramasRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/browse/documentaries': {
      id: '/browse/documentaries'
      path: '/documentaries'
      fullPath: '/browse/documentaries'
      preLoaderRoute: typeof BrowseDocumentariesRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/browse/cartoons': {
      id: '/browse/cartoons'
      path: '/cartoons'
      fullPath: '/browse/cartoons'
      preLoaderRoute: typeof BrowseCartoonsRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/titles': {
      id: '/_authenticated/admin/titles'
      path: '/titles'
      fullPath: '/admin/titles'
      preLoaderRoute: typeof AuthenticatedAdminTitlesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/taxonomy': {
      id: '/_authenticated/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AuthenticatedAdminTaxonomyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sync': {
      id: '/_authenticated/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AuthenticatedAdminSyncRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/titles/$id': {
      id: '/_authenticated/admin/titles/$id'
      path: '/$id'
      fullPath: '/admin/titles/$id'
      preLoaderRoute: typeof AuthenticatedAdminTitlesIdRouteImport
      parentRoute: typeof AuthenticatedAdminTitlesRoute
    }
  }
}

interface AuthenticatedAdminTitlesRouteChildren {
  AuthenticatedAdminTitlesIdRoute: typeof AuthenticatedAdminTitlesIdRoute
}

const AuthenticatedAdminTitlesRouteChildren: AuthenticatedAdminTitlesRouteChildren =
  {
    AuthenticatedAdminTitlesIdRoute: AuthenticatedAdminTitlesIdRoute,
  }

const AuthenticatedAdminTitlesRouteWithChildren =
  AuthenticatedAdminTitlesRoute._addFileChildren(
    AuthenticatedAdminTitlesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSyncRoute: typeof AuthenticatedAdminSyncRoute
  AuthenticatedAdminTaxonomyRoute: typeof AuthenticatedAdminTaxonomyRoute
  AuthenticatedAdminTitlesRoute: typeof AuthenticatedAdminTitlesRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
    AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
    AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
    AuthenticatedAdminSyncRoute: AuthenticatedAdminSyncRoute,
    AuthenticatedAdminTaxonomyRoute: AuthenticatedAdminTaxonomyRoute,
    AuthenticatedAdminTitlesRoute: AuthenticatedAdminTitlesRouteWithChildren,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BrowseRouteChildren {
  BrowseCartoonsRoute: typeof BrowseCartoonsRoute
  BrowseDocumentariesRoute: typeof BrowseDocumentariesRoute
  BrowseDramasRoute: typeof BrowseDramasRoute
  BrowseMoviesRoute: typeof BrowseMoviesRoute
  BrowseSeriesRoute: typeof BrowseSeriesRoute
}

const BrowseRouteChildren: BrowseRouteChildren = {
  BrowseCartoonsRoute: BrowseCartoonsRoute,
  BrowseDocumentariesRoute: BrowseDocumentariesRoute,
  BrowseDramasRoute: BrowseDramasRoute,
  BrowseMoviesRoute: BrowseMoviesRoute,
  BrowseSeriesRoute: BrowseSeriesRoute,
}

const BrowseRouteWithChildren =
  BrowseRoute._addFileChildren(BrowseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRouteWithChildren,
  PricingRoute: PricingRoute,
  SearchRoute: SearchRoute,
  TitleSlugRoute: TitleSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
