/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as TitleSlugRouteImport } from './routes/title.$slug'
import { Route as BrowseSeriesRouteImport } from './routes/browse.series'
import { Route as BrowseMoviesRouteImport } from './routes/browse.movies'
import { Route as BrowseDramasRouteImport } from './routes/browse.dramas'
import { Route as BrowseDocumentariesRouteImport } from './routes/browse.documentaries'
import { Route as BrowseCartoonsRouteImport } from './routes/browse.cartoons'
import { Route as BrowseAppsRouteImport } from './routes/browse.apps'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppsSlugRouteImport } from './routes/apps.$slug'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiIngestTrendingMoviesRouteImport } from './routes/api/ingest/trending-movies'
import { Route as ApiIngestPopularTvRouteImport } from './routes/api/ingest/popular-tv'
import { Route as ApiIngestPopularMoviesRouteImport } from './routes/api/ingest/popular-movies'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTitlesRouteImport } from './routes/_authenticated/admin/titles'
import { Route as AuthenticatedAdminTaxonomyRouteImport } from './routes/_authenticated/admin/taxonomy'
import { Route as AuthenticatedAdminSyncRouteImport } from './routes/_authenticated/admin/sync'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminDownloadsRouteImport } from './routes/_authenticated/admin/downloads'
import { Route as AuthenticatedAdminContentIngestionRouteImport } from './routes/_authenticated/admin/content-ingestion'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAppsRouteImport } from './routes/_authenticated/admin/apps'
import { Route as ApiPublicDownloadIdRouteImport } from './routes/api/public/download.$id'
import { Route as AuthenticatedAdminTitlesIdRouteImport } from './routes/_authenticated/admin/titles.$id'
import { Route as AuthenticatedAdminAppsIdRouteImport } from './routes/_authenticated/admin/apps.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSlugRoute = TitleSlugRouteImport.update({
  id: '/title/$slug',
  path: '/title/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSeriesRoute = BrowseSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseMoviesRoute = BrowseMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseDramasRoute = BrowseDramasRouteImport.update({
  id: '/dramas',
  path: '/dramas',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseDocumentariesRoute = BrowseDocumentariesRouteImport.update({
  id: '/documentaries',
  path: '/documentaries',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseCartoonsRoute = BrowseCartoonsRouteImport.update({
  id: '/cartoons',
  path: '/cartoons',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseAppsRoute = BrowseAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => BrowseRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestTrendingMoviesRoute = ApiIngestTrendingMoviesRouteImport.update({
  id: '/api/ingest/trending-movies',
  path: '/api/ingest/trending-movies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestPopularTvRoute = ApiIngestPopularTvRouteImport.update({
  id: '/api/ingest/popular-tv',
  path: '/api/ingest/popular-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestPopularMoviesRoute = ApiIngestPopularMoviesRouteImport.update({
  id: '/api/ingest/popular-movies',
  path: '/api/ingest/popular-movies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTitlesRoute =
  AuthenticatedAdminTitlesRouteImport.update({
    id: '/titles',
    path: '/titles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTaxonomyRoute =
  AuthenticatedAdminTaxonomyRouteImport.update({
    id: '/taxonomy',
    path: '/taxonomy',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSyncRoute = AuthenticatedAdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDownloadsRoute =
  AuthenticatedAdminDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentIngestionRoute =
  AuthenticatedAdminContentIngestionRouteImport.update({
    id: '/content-ingestion',
    path: '/content-ingestion',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAppsRoute = AuthenticatedAdminAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicDownloadIdRoute = ApiPublicDownloadIdRouteImport.update({
  id: '/api/public/download/$id',
  path: '/api/public/download/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTitlesIdRoute =
  AuthenticatedAdminTitlesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTitlesRoute,
  } as any)
const AuthenticatedAdminAppsIdRoute =
  AuthenticatedAdminAppsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminAppsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRouteWithChildren
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/browse/apps': typeof BrowseAppsRoute
  '/browse/cartoons': typeof BrowseCartoonsRoute
  '/browse/documentaries': typeof BrowseDocumentariesRoute
  '/browse/dramas': typeof BrowseDramasRoute
  '/browse/movies': typeof BrowseMoviesRoute
  '/browse/series': typeof BrowseSeriesRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/admin/apps': typeof AuthenticatedAdminAppsRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/content-ingestion': typeof AuthenticatedAdminContentIngestionRoute
  '/admin/downloads': typeof AuthenticatedAdminDownloadsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/titles': typeof AuthenticatedAdminTitlesRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/ingest/popular-movies': typeof ApiIngestPopularMoviesRoute
  '/api/ingest/popular-tv': typeof ApiIngestPopularTvRoute
  '/api/ingest/trending-movies': typeof ApiIngestTrendingMoviesRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/apps/$id': typeof AuthenticatedAdminAppsIdRoute
  '/admin/titles/$id': typeof AuthenticatedAdminTitlesIdRoute
  '/api/public/download/$id': typeof ApiPublicDownloadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRouteWithChildren
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/browse/apps': typeof BrowseAppsRoute
  '/browse/cartoons': typeof BrowseCartoonsRoute
  '/browse/documentaries': typeof BrowseDocumentariesRoute
  '/browse/dramas': typeof BrowseDramasRoute
  '/browse/movies': typeof BrowseMoviesRoute
  '/browse/series': typeof BrowseSeriesRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/admin/apps': typeof AuthenticatedAdminAppsRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/content-ingestion': typeof AuthenticatedAdminContentIngestionRoute
  '/admin/downloads': typeof AuthenticatedAdminDownloadsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/titles': typeof AuthenticatedAdminTitlesRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/ingest/popular-movies': typeof ApiIngestPopularMoviesRoute
  '/api/ingest/popular-tv': typeof ApiIngestPopularTvRoute
  '/api/ingest/trending-movies': typeof ApiIngestTrendingMoviesRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/apps/$id': typeof AuthenticatedAdminAppsIdRoute
  '/admin/titles/$id': typeof AuthenticatedAdminTitlesIdRoute
  '/api/public/download/$id': typeof ApiPublicDownloadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/browse': typeof BrowseRouteWithChildren
  '/download': typeof DownloadRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/browse/apps': typeof BrowseAppsRoute
  '/browse/cartoons': typeof BrowseCartoonsRoute
  '/browse/documentaries': typeof BrowseDocumentariesRoute
  '/browse/dramas': typeof BrowseDramasRoute
  '/browse/movies': typeof BrowseMoviesRoute
  '/browse/series': typeof BrowseSeriesRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/_authenticated/admin/apps': typeof AuthenticatedAdminAppsRouteWithChildren
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/content-ingestion': typeof AuthenticatedAdminContentIngestionRoute
  '/_authenticated/admin/downloads': typeof AuthenticatedAdminDownloadsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/_authenticated/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/_authenticated/admin/titles': typeof AuthenticatedAdminTitlesRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/ingest/popular-movies': typeof ApiIngestPopularMoviesRoute
  '/api/ingest/popular-tv': typeof ApiIngestPopularTvRoute
  '/api/ingest/trending-movies': typeof ApiIngestTrendingMoviesRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/apps/$id': typeof AuthenticatedAdminAppsIdRoute
  '/_authenticated/admin/titles/$id': typeof AuthenticatedAdminTitlesIdRoute
  '/api/public/download/$id': typeof ApiPublicDownloadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/download'
    | '/pricing'
    | '/reset-password'
    | '/search'
    | '/account'
    | '/watchlist'
    | '/apps/$slug'
    | '/auth/callback'
    | '/browse/apps'
    | '/browse/cartoons'
    | '/browse/documentaries'
    | '/browse/dramas'
    | '/browse/movies'
    | '/browse/series'
    | '/title/$slug'
    | '/watch/$slug'
    | '/admin/apps'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/content-ingestion'
    | '/admin/downloads'
    | '/admin/plans'
    | '/admin/reviews'
    | '/admin/sync'
    | '/admin/taxonomy'
    | '/admin/titles'
    | '/admin/users'
    | '/api/ingest/popular-movies'
    | '/api/ingest/popular-tv'
    | '/api/ingest/trending-movies'
    | '/api/public/stripe-webhook'
    | '/admin/'
    | '/admin/apps/$id'
    | '/admin/titles/$id'
    | '/api/public/download/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/download'
    | '/pricing'
    | '/reset-password'
    | '/search'
    | '/account'
    | '/watchlist'
    | '/apps/$slug'
    | '/auth/callback'
    | '/browse/apps'
    | '/browse/cartoons'
    | '/browse/documentaries'
    | '/browse/dramas'
    | '/browse/movies'
    | '/browse/series'
    | '/title/$slug'
    | '/watch/$slug'
    | '/admin/apps'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/content-ingestion'
    | '/admin/downloads'
    | '/admin/plans'
    | '/admin/reviews'
    | '/admin/sync'
    | '/admin/taxonomy'
    | '/admin/titles'
    | '/admin/users'
    | '/api/ingest/popular-movies'
    | '/api/ingest/popular-tv'
    | '/api/ingest/trending-movies'
    | '/api/public/stripe-webhook'
    | '/admin/apps/$id'
    | '/admin/titles/$id'
    | '/api/public/download/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/download'
    | '/pricing'
    | '/reset-password'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/watchlist'
    | '/apps/$slug'
    | '/auth/callback'
    | '/browse/apps'
    | '/browse/cartoons'
    | '/browse/documentaries'
    | '/browse/dramas'
    | '/browse/movies'
    | '/browse/series'
    | '/title/$slug'
    | '/watch/$slug'
    | '/_authenticated/admin/apps'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/content-ingestion'
    | '/_authenticated/admin/downloads'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/sync'
    | '/_authenticated/admin/taxonomy'
    | '/_authenticated/admin/titles'
    | '/_authenticated/admin/users'
    | '/api/ingest/popular-movies'
    | '/api/ingest/popular-tv'
    | '/api/ingest/trending-movies'
    | '/api/public/stripe-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/apps/$id'
    | '/_authenticated/admin/titles/$id'
    | '/api/public/download/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  BrowseRoute: typeof BrowseRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  AppsSlugRoute: typeof AppsSlugRoute
  TitleSlugRoute: typeof TitleSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  ApiIngestPopularMoviesRoute: typeof ApiIngestPopularMoviesRoute
  ApiIngestPopularTvRoute: typeof ApiIngestPopularTvRoute
  ApiIngestTrendingMoviesRoute: typeof ApiIngestTrendingMoviesRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicDownloadIdRoute: typeof ApiPublicDownloadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$slug': {
      id: '/title/$slug'
      path: '/title/$slug'
      fullPath: '/title/$slug'
      preLoaderRoute: typeof TitleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/series': {
      id: '/browse/series'
      path: '/series'
      fullPath: '/browse/series'
      preLoaderRoute: typeof BrowseSeriesRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/browse/movies': {
      id: '/browse/movies'
      path: '/movies'
      fullPath: '/browse/movies'
      preLoaderRoute: typeof BrowseMoviesRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/browse/dramas': {
      id: '/browse/dramas'
      path: '/dramas'
      fullPath: '/browse/dramas'
      preLoaderRoute: typeof BrowseDramasRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/browse/documentaries': {
      id: '/browse/documentaries'
      path: '/documentaries'
      fullPath: '/browse/documentaries'
      preLoaderRoute: typeof BrowseDocumentariesRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/browse/cartoons': {
      id: '/browse/cartoons'
      path: '/cartoons'
      fullPath: '/browse/cartoons'
      preLoaderRoute: typeof BrowseCartoonsRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/browse/apps': {
      id: '/browse/apps'
      path: '/apps'
      fullPath: '/browse/apps'
      preLoaderRoute: typeof BrowseAppsRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/trending-movies': {
      id: '/api/ingest/trending-movies'
      path: '/api/ingest/trending-movies'
      fullPath: '/api/ingest/trending-movies'
      preLoaderRoute: typeof ApiIngestTrendingMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/popular-tv': {
      id: '/api/ingest/popular-tv'
      path: '/api/ingest/popular-tv'
      fullPath: '/api/ingest/popular-tv'
      preLoaderRoute: typeof ApiIngestPopularTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/popular-movies': {
      id: '/api/ingest/popular-movies'
      path: '/api/ingest/popular-movies'
      fullPath: '/api/ingest/popular-movies'
      preLoaderRoute: typeof ApiIngestPopularMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/titles': {
      id: '/_authenticated/admin/titles'
      path: '/titles'
      fullPath: '/admin/titles'
      preLoaderRoute: typeof AuthenticatedAdminTitlesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/taxonomy': {
      id: '/_authenticated/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AuthenticatedAdminTaxonomyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sync': {
      id: '/_authenticated/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AuthenticatedAdminSyncRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/downloads': {
      id: '/_authenticated/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AuthenticatedAdminDownloadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content-ingestion': {
      id: '/_authenticated/admin/content-ingestion'
      path: '/content-ingestion'
      fullPath: '/admin/content-ingestion'
      preLoaderRoute: typeof AuthenticatedAdminContentIngestionRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/apps': {
      id: '/_authenticated/admin/apps'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AuthenticatedAdminAppsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/download/$id': {
      id: '/api/public/download/$id'
      path: '/api/public/download/$id'
      fullPath: '/api/public/download/$id'
      preLoaderRoute: typeof ApiPublicDownloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/titles/$id': {
      id: '/_authenticated/admin/titles/$id'
      path: '/$id'
      fullPath: '/admin/titles/$id'
      preLoaderRoute: typeof AuthenticatedAdminTitlesIdRouteImport
      parentRoute: typeof AuthenticatedAdminTitlesRoute
    }
    '/_authenticated/admin/apps/$id': {
      id: '/_authenticated/admin/apps/$id'
      path: '/$id'
      fullPath: '/admin/apps/$id'
      preLoaderRoute: typeof AuthenticatedAdminAppsIdRouteImport
      parentRoute: typeof AuthenticatedAdminAppsRoute
    }
  }
}

interface AuthenticatedAdminAppsRouteChildren {
  AuthenticatedAdminAppsIdRoute: typeof AuthenticatedAdminAppsIdRoute
}

const AuthenticatedAdminAppsRouteChildren: AuthenticatedAdminAppsRouteChildren =
  {
    AuthenticatedAdminAppsIdRoute: AuthenticatedAdminAppsIdRoute,
  }

const AuthenticatedAdminAppsRouteWithChildren =
  AuthenticatedAdminAppsRoute._addFileChildren(
    AuthenticatedAdminAppsRouteChildren,
  )

interface AuthenticatedAdminTitlesRouteChildren {
  AuthenticatedAdminTitlesIdRoute: typeof AuthenticatedAdminTitlesIdRoute
}

const AuthenticatedAdminTitlesRouteChildren: AuthenticatedAdminTitlesRouteChildren =
  {
    AuthenticatedAdminTitlesIdRoute: AuthenticatedAdminTitlesIdRoute,
  }

const AuthenticatedAdminTitlesRouteWithChildren =
  AuthenticatedAdminTitlesRoute._addFileChildren(
    AuthenticatedAdminTitlesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAppsRoute: typeof AuthenticatedAdminAppsRouteWithChildren
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminContentIngestionRoute: typeof AuthenticatedAdminContentIngestionRoute
  AuthenticatedAdminDownloadsRoute: typeof AuthenticatedAdminDownloadsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSyncRoute: typeof AuthenticatedAdminSyncRoute
  AuthenticatedAdminTaxonomyRoute: typeof AuthenticatedAdminTaxonomyRoute
  AuthenticatedAdminTitlesRoute: typeof AuthenticatedAdminTitlesRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAppsRoute: AuthenticatedAdminAppsRouteWithChildren,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
    AuthenticatedAdminContentIngestionRoute:
      AuthenticatedAdminContentIngestionRoute,
    AuthenticatedAdminDownloadsRoute: AuthenticatedAdminDownloadsRoute,
    AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
    AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
    AuthenticatedAdminSyncRoute: AuthenticatedAdminSyncRoute,
    AuthenticatedAdminTaxonomyRoute: AuthenticatedAdminTaxonomyRoute,
    AuthenticatedAdminTitlesRoute: AuthenticatedAdminTitlesRouteWithChildren,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BrowseRouteChildren {
  BrowseAppsRoute: typeof BrowseAppsRoute
  BrowseCartoonsRoute: typeof BrowseCartoonsRoute
  BrowseDocumentariesRoute: typeof BrowseDocumentariesRoute
  BrowseDramasRoute: typeof BrowseDramasRoute
  BrowseMoviesRoute: typeof BrowseMoviesRoute
  BrowseSeriesRoute: typeof BrowseSeriesRoute
}

const BrowseRouteChildren: BrowseRouteChildren = {
  BrowseAppsRoute: BrowseAppsRoute,
  BrowseCartoonsRoute: BrowseCartoonsRoute,
  BrowseDocumentariesRoute: BrowseDocumentariesRoute,
  BrowseDramasRoute: BrowseDramasRoute,
  BrowseMoviesRoute: BrowseMoviesRoute,
  BrowseSeriesRoute: BrowseSeriesRoute,
}

const BrowseRouteWithChildren =
  BrowseRoute._addFileChildren(BrowseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  BrowseRoute: BrowseRouteWithChildren,
  DownloadRoute: DownloadRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  AppsSlugRoute: AppsSlugRoute,
  TitleSlugRoute: TitleSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  ApiIngestPopularMoviesRoute: ApiIngestPopularMoviesRoute,
  ApiIngestPopularTvRoute: ApiIngestPopularTvRoute,
  ApiIngestTrendingMoviesRoute: ApiIngestTrendingMoviesRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicDownloadIdRoute: ApiPublicDownloadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
